var db, expFetcher, userUpdateFunction, levelUpChannel, lbPositionFunction;
var {EmbedBuilder, AttachmentBuilder, SlashCommandBuilder, InteractionContextType} = require('discord.js');
var util = require('../util');
var canvas = require('canvas');
var fs = require('fs');
var fontList = require('font-list');

module.exports = (client, logChannels, config, botContext)=>{
    var calculateLevel = exp=>exp>=config.firstRankExpLength?~~(exp/config.rankExpLength)+1:0;
    async function onReady() {
        db = botContext.db;
        db.prepare(`
            CREATE TABLE IF NOT EXISTS user_exp (
                user_id INTEGER PRIMARY KEY,
                exp INTEGER DEFAULT 0
            )
        `).run();
        expFetcher = db.prepare("SELECT exp FROM user_exp WHERE user_id = ?");
        userUpdateFunction = db.prepare(`
            INSERT INTO user_exp (user_id, exp)
            VALUES (:user_id, :exp)
            ON CONFLICT(user_id) DO UPDATE SET
                exp = excluded.exp
        `);
        lbPositionFunction = db.prepare(`
            WITH leaderboard AS (
                SELECT user_id, exp, RANK() OVER (ORDER BY exp DESC) AS rank FROM user_exp
            ) SELECT rank FROM leaderboard WHERE user_id = ?
        `);
        levelUpChannel = await client.channels.fetch(config.levelUpChannelId);
        if(!(await fontList.getFonts()).map(f=>f.replaceAll("\"","")).includes("Roboto")) {
            console.warn("WARNING: The Roboto font is not installed. The image generated by the /rank command might look strange.");
        }
    }

    async function onMessage(message) {
        var id = message.author.id;
        var fetchedData = expFetcher.get(id);
        var userExp = fetchedData?.exp || 0;
        if(isNaN(userExp)) userExp = 0;
        userExp++;
        await setExp(message.member, userExp);
    }


    async function setAddExpCmdHandler(isSlash, params, ctx, commandName) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        var user = await util.getMember(botContext.guild, params.member);
        if(!user) {
            await reply("Valid member was not provided.");
            return;
        }
        if(!util.hasRole(ctx.member, config.helperPlusRoleList) && !config.botOwners.includes(ctx.member.id)) {
            await reply("no");
            return;
        }
        var exp = parseInt(params.exp);
        if(!Number.isInteger(exp)) {
            await reply("Invalid exp value provided.");
            return;
        }
        if(["addxp","addexp"].includes(commandName)) {
            var fetchedData = expFetcher.get(user.id);
            var userExp = fetchedData?.exp || 0;
            exp+=userExp;
        }
        await setExp(user, exp);
        await reply({content:`${user}'s experience was set to ${exp}! Their level is now ${calculateLevel(exp)}.`});
        return;
    }

    async function delUserLvlsCmdHandler(isSlash, params, ctx) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        if(!util.hasRole(ctx.member, config.helperPlusRoleList) && !config.botOwners.includes(ctx.member.id)) {
            await reply("no");
            return;
        }
        if(!expFetcher.get(params.member)) {
            await reply("User ID is not in level database.");
            return;
        }
        db.prepare(`DELETE FROM user_exp WHERE user_id = ?`).run(params.member);
        await reply(`Deleted user \`${params.member}\` from level database.`);
        return;
    }

    async function setLevelCmdHandler(isSlash, params, ctx) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        var user = await util.getMember(botContext.guild, params.member);
        if(!user) {
            await reply("Valid member was not provided.");
            return;
        }
        if(!util.hasRole(ctx.member, config.helperPlusRoleList) && !config.botOwners.includes(ctx.member.id)) {
            await reply("no");
            return;
        }
        var level = parseInt(params.level);
        if(!Number.isInteger(level)) {
            await reply("Invalid level value provided.");
            return;
        }
        var exp = (level > 1 ? ((level - 1) * config.rankExpLength) : config.firstRankExpLength * level);
        await setExp(user, exp);
        await reply({content:`${user}'s level was set to ${level}! Their experience is now ${exp}.`});
        return;
    }

    async function rankCmdHandler(isSlash, params, ctx) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        var member = await util.getMember(botContext.guild, params.member);
        if(!member) member = await util.getMember(botContext.guild, ctx.member);
        var fetchedExpData = expFetcher.get(member.id);
        var fetchedRankData = lbPositionFunction.get(member.id);
        var userExp = fetchedExpData?.exp || 0;
        var rank = fetchedRankData?.rank || NaN;
        if(isNaN(userExp)) userExp = 0;
        var userProgress = calculateProgress(userExp);

        var rankCanvas = canvas.createCanvas(1094, 272);
        var ctx = rankCanvas.getContext('2d');
        ctx.save();

        ctx.fillStyle = "rgb(33,39,51)";
        ctx.fillRect(0, 0, rankCanvas.width, rankCanvas.height);

        ctx.beginPath();

        ctx.arc(136, 136, 128, 0, Math.PI * 2);
        ctx.clip();
        var avatar = await canvas.loadImage(member.user.displayAvatarURL({extension:"png",size:256}));
        ctx.drawImage(avatar, 8, 8);

        ctx.closePath();
        ctx.restore();

        ctx.strokeStyle = "2px black";
        ctx.arc(136, 136, 128, 0, Math.PI * 2);
        ctx.stroke();

        var fontSize = 70;
        ctx.font = `normal ${fontSize}px "Roboto"`;
        while(ctx.measureText(member.displayName).width > 500) {
            fontSize--;
            ctx.font = `normal ${fontSize}px "Roboto"`;
        }
        ctx.fillStyle = "white";
        ctx.fillText(member.displayName, 280, 153, 500);
        
        var percentage = userProgress.xpIntoLevel / (userProgress.level?config.rankExpLength:config.firstRankExpLength);
        drawLevelBar(ctx, percentage);

        ctx.save();
        ctx.font = 'normal 20px "Roboto"';
        ctx.textAlign = 'right';
        ctx.fillStyle = "rgb(93,99,111)";
        ctx.fillText(`EXP: ${userExp}/${userProgress.xpForNextLevel}`, 970, 164);
        ctx.font = 'normal 30px "Roboto"';
        ctx.fillStyle = "rgb(193,199,211)";
        ctx.fillText(`LEVEL ${userProgress.level}`, 970, 140);
        if(!isNaN(rank)) {
            ctx.font = 'normal 25px "Roboto"';
            ctx.fillStyle = "white";
            ctx.textAlign = "left";
            ctx.fillText(`#${rank} on Leaderboard`, 300, 250);
        }
        ctx.restore();

        var stream = rankCanvas.createPNGStream();
        var attachment = new AttachmentBuilder(stream,{name: member.user.id+"_rank.png"});
        await reply({files:[attachment]});
    }

    async function fixRolesCmdHandler(isSlash, params, ctx) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        var member = await util.getMember(params.member);
        if(!member) member = await util.getMember(botContext.guild, isSlash?ctx.user:ctx.author);
        await updateRoles(member);
        await reply("Attempted to add roles based on current XP!");
    }

    async function leaderboardCmdHandler(isSlash, params, ctx) {
        var reply = util.ctxReplier(ctx, isSlash);
        if(isSlash) await ctx.deferReply();
        var topTen = db.prepare(`SELECT CAST(user_id AS varchar) AS user_id,exp from user_exp ORDER BY exp DESC LIMIT 10`).all();
        var description = "";
        for(let rank = 1; rank <= topTen.length; rank++) {
            let user = topTen[rank-1];
            let userProgress = calculateProgress(user.exp);
            let username;
            try {
                let discordUser = await client.users.fetch(user.user_id);
                username = discordUser.username;
            } catch(err) {}
            description += `**#${rank}: <@${user.user_id}>** ${username?"("+username+")":""}\n\tLevel ${userProgress.level}\n\tEXP: ${user.exp}/${userProgress.xpForNextLevel}\n\n`;
        }
        var leaderboardEmbed = new EmbedBuilder();
        leaderboardEmbed.setTitle("Leaderboard");
        leaderboardEmbed.setDescription(description);
        leaderboardEmbed.setColor("Gold");
        await reply({embeds:[leaderboardEmbed]});
    }

    async function setExp(member, exp) {
        var fetchedData = expFetcher.get(member.id);
        var userExp = fetchedData?.exp || 0;
        if(isNaN(userExp)) userExp = 0;
        var currentLevel = calculateLevel(userExp);
        userUpdateFunction.run({user_id:member.id,exp:exp});
        var newLevel = calculateLevel(exp);
        if(newLevel > currentLevel) {
            var roleAddedId = await updateRoles(member);
            var description = `**Congratulations!**\n${member} is now level ${newLevel}!!!`;
            if(roleAddedId) {
                description += `\nThey have now also earned <@&${roleAddedId}>! Yippee!`;
            }
            let levelUpEmbed = new EmbedBuilder()
            .setAuthor({name: member.displayName, iconURL: member.user.displayAvatarURL({extension:"png",size:2048})})
            .setTitle(`LEVEL UP!`)
            .setDescription(description)
            .setTimestamp()
            .setColor(roleAddedId?"Gold":"Green");
            if(roleAddedId) {
                await levelUpChannel.send({content:member.toString(),embeds:[levelUpEmbed]});
            } else {
                await levelUpChannel.send({embeds: [levelUpEmbed]});
            }
        }
    }

    async function updateRoles(member) {
        var fetchedData = expFetcher.get(member.id);
        var userExp = fetchedData?.exp || 0;
        if(isNaN(userExp)) userExp = 0;
        var level = calculateLevel(userExp);
        var addedARole = false;
        var topRoleId = null;
        for(var i in config.levelUpRoles) {
            if(level>=config.levelUpRoles[i][0]) {
                if(util.hasRole(member, config.levelUpRoles[i][1])) {
                    continue;
                }
                addedARole = true;
                topRoleId = config.levelUpRoles[i][1];
                member.roles.add(topRoleId);
                continue;
            }
            break;
        }
        if(!addedARole) return false;
        return topRoleId;
    }

    function drawLevelBar(ctx, percent) {
        drawCylinder(ctx, "rgb(93,99,111)", 650);
        drawCylinder(ctx, "lightgreen", ~~(percent*650));
    }

    function drawCylinder(ctx, color, lengthOfGap) {
        ctx.beginPath();
        ctx.fillStyle = color; 
        ctx.arc(300, 194, 20, Math.PI/2, -Math.PI/2, false);
        ctx.fill();

        ctx.fillRect(300, 174, lengthOfGap, 40);

        ctx.arc(300+lengthOfGap, 194, 20, Math.PI/2, -Math.PI/2, true);
        ctx.fill();

        ctx.closePath();
    }

    function calculateProgress(exp) {
        var level = calculateLevel(exp);
        var xpIntoLevel = level > 0 ? (exp % config.rankExpLength) : (exp % config.firstRankExpLength);
        var xpForNextLevel = level > 0 ? (level * config.rankExpLength) : config.firstRankExpLength;
        return {
            level,
            xpIntoLevel,
            xpForNextLevel
        };
    }

    return {
        onReady,
        onMessage,
        commands: {
            rank: {
                prefix: {
                    name: "rank",
                    params: [
                        {
                            name: "member",
                            type: "member",
                            optional: true
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("rank")
                    .setDescription("Shows a member's level and leaderboard status")
                    .addUserOption(option=>option.setName("member").setDescription("Member to see the rank of, defaults to your own"))
                },
                handler: rankCmdHandler
            },
            leaderboard: {
                prefix: {
                    name: "leaderboard",
                    aliases: ["lb"],
                    params: []
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("leaderboard")
                    .setDescription("Shows a top 10 leaderboard, aka lb")
                },
                handler: leaderboardCmdHandler
            },
            fixroles: {
                prefix: {
                    name: "fixroles",
                    params: [
                        {
                            name: "member",
                            type: "member",
                            optional: true
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("fixroles")
                    .setDescription("Fix the roles applied to a user based on their level.")
                    .addUserOption(option=>option.setName("member").setDescription("Member whose roles to fix, defaults to you"))
                },
                handler: fixRolesCmdHandler
            },
            setlevel: {
                prefix: {
                    name: "setlevel",
                    params: [
                        {
                            name: "member",
                            type: "member"
                        },
                        {
                            name: "level",
                            type: "text"
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("setlevel")
                    .setDescription("Set the current level of a user, Helper+ only")
                    .addUserOption(option=>option.setName("member").setDescription("The user").setRequired(true))
                    .addIntegerOption(option=>option.setName("level").setDescription("Level").setRequired(true))
                    .setContexts(InteractionContextType.Guild)
                },
                handler: setLevelCmdHandler
            },
            deluserlvls: {
                prefix: {
                    name: "deluserlvls",
                    params: [
                        {
                            name: "member",
                            type: "text"
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("deluserlvls")
                    .setDescription("Remove a user from the leaderboard, Helper+ only")
                    .addStringOption(option=>option.setName("member").setDescription("User ID to remove from leaderboard").setRequired(true))
                    .setContexts(InteractionContextType.Guild)
                },
                handler: delUserLvlsCmdHandler
            },
            setexp: {
                prefix: {
                    name: "setexp",
                    aliases: ["setxp"],
                    params: [
                        {
                            name: "member",
                            type: "member"
                        },
                        {
                            name: "exp",
                            type: "text"
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("setexp")
                    .setDescription("Sets the leaderboard experience for a user, Helper+ only")
                    .addUserOption(option=>option.setName("member").setDescription("The user").setRequired(true))
                    .addIntegerOption(option=>option.setName("exp").setDescription("EXP Points").setRequired(true))
                    .setContexts(InteractionContextType.Guild)
                },
                handler: setAddExpCmdHandler
            },
            addexp: {
                prefix: {
                    name: "addexp",
                    aliases: ["addxp"],
                    params: [
                        {
                            name: "member",
                            type: "member"
                        },
                        {
                            name: "exp",
                            type: "text"
                        }
                    ]
                },
                slash: {
                    data: new SlashCommandBuilder()
                    .setName("addexp")
                    .setDescription("Adds leaderboard experience to the current total of a user, Helper+ only")
                    .addUserOption(option=>option.setName("member").setDescription("The user").setRequired(true))
                    .addIntegerOption(option=>option.setName("exp").setDescription("EXP Points").setRequired(true))
                    .setContexts(InteractionContextType.Guild)
                },
                handler: setAddExpCmdHandler
            }
        }
    }
};
